//
//  SwipeSelectorViewControllerDataSource.swift
//  SwipeSelectorKit
//
//  Created by Alex Takahashi on 10/15/20.
//

import Foundation
import UIKit

public struct SwipeSelectorViewControllerDataSource {
    //our datasource
    public let items: [SwipeSelectorModel] =
        [SwipeSelectorModel(title: "palette \n playlists made for you", subtitle: [""], image: UIImage(named: "palette"), genre: "swipe to continue!", sound: "drake", soundTitle: "", bio: ""),
         SwipeSelectorModel(title: "Drake", subtitle: ["Hotline Bling", "Headlines", "Toosie Slide", "God's Plan", "One Dance", "In My Feelings"], image: UIImage(named: "drake"), genre: "Rap", sound: "richbrian", soundTitle: "Now Playing: God's Plan - Drake", bio: "Canadian rapper and vocalist Drake sustained a high-level commercial presence shortly after he hit the scene in 2006, whether with his own chart-topping releases or a long string of guest appearances on hits by the likes of Lil Wayne, Rihanna, and A$AP Rocky. Thanks to his introspective rap style, his sensitive R&B crooning, and his gold-touch songwriting, each one of his albums -- from 2011's Take Care to 2018's Scorpion -- topped charts worldwide, and singles like the Grammy-winning 'Hotline Bling' and many of his mixtapes did too."),
         SwipeSelectorModel(title: "Rich Brian", subtitle: ["Love in my Pocket", "100 Degrees", "Midsummer Madness", "Yellow", "Sometimes", "When You Come Home"], image: UIImage(named: "richbrian"), genre: "Alternative Rap", sound: "joji", soundTitle: "Now Playing: Glow Like That - Rich Brian", bio: "Rapper and vocalist Rich Brian has recently experienced major mainstream success--from collaborating with the likes of 21 Savage, Offset, and Playboi Carti, to selling out shows and playing festivals around the world. Brian’s debut project Amen, released in February 2018, garnered widespread critical acclaim and topped the iTunes Hip-Hop charts - a first in history for an Asian musician."),
         SwipeSelectorModel(title: "Joji", subtitle: ["Slow Dancing in the Dark", "Daylight", "Tick Tock", "Ew", "Run"], image: UIImage(named: "joji"), genre: "Alternative R&B", sound: "niki", soundTitle: "Now Playing: Slow Dancing in the Dark - Joji", bio: "Joji is one of the most enthralling artists of the digital age. His latest album Nectar arrives as an eagerly anticipated follow-up to Joji’s RIAA Gold-certified first full-length album BALLADS 1, which topped the Billboard R&B / Hip-Hop Charts and has amassed 3.6B+ streams to date. The “first music superstar of his kind” (Office), Joji is back with a cinematic and contemplative follow-up that he describes as having “a sense of urgency but calm.”"),
         SwipeSelectorModel(title: "Niki", subtitle: ["Indigo", "Nightcrawlers", "lowkey", "I Like U", "See U Never", "La La Lost You"], image: UIImage(named: "niki"), genre: "R&B", sound: "lauv", soundTitle: "Now Playing: I Like U - NIKI", bio: "Releasing her breakout EP Zephyr in 2018, Nicole Zefanya, AKA NIKI, garnered critical acclaim from the likes of Highsnobiety, Pitchfork, Nylon, and Clash, among others. She joined the artist collective 88rising that same year, proving integral to their compilations, Head in the Clouds parts I and II. Her remarkable versatility and genre-bending artistry has brought her fans and praise from across the globe. NIKI closed out 2018 as one of Complex's ‘Best New Artists’, and her output the following year only further solidified the designation."),
         SwipeSelectorModel(title: "Lauv", subtitle: ["Modern Loneliness", "Love Like That", "Easy Love", "Tattoos Together", "Lonely Eyes", "Bracelet"], image: UIImage(named: "lauv.jpg"), genre: "Bedroom Pop", sound: "ari", soundTitle: "Now Playing: I Like Me Better - LAUV", bio: "For more than five years, Lauv has quietly and steadily become one of pop’s brightest rising stars. He has released his music completely independently with 5 billion streams to his name. He has written for some of the biggest stars in the world, performed on late night talk shows, played stadiums opening for Ed Sheeran, and sold out shows in 21 countries as a headliner. With millions of fans already on board for his music and his message, and a sound that’s built for a stadium-size audience, it’s sure shaping up to be a wild ride."),
         SwipeSelectorModel(title: "Ariana Grande", subtitle: ["off the table (with The Weeknd)", "One Last Time", "shut up", "34 + 35", "just like magic", "my hair"], image: UIImage(named: "arianagrande.jpg"), genre: "Pop", sound: "max", soundTitle: "Now Playing: thank u, next - Ariana Grande", bio: "Ariana Grande is perhaps the quintessential pop star of the last half of the 2010s, capturing the era's spirit and style. Emerging in 2013 with the hit single 'The Way', Grande initially appeared to be the heir to the throne of Mariah Carey, due in part to her powerhouse vocals. With its Babyface production, her debut Yours Truly underscored her debt to '90s R&B, but Grande quickly incorporated hip-hop and EDM into her music."),
         SwipeSelectorModel(title: "Max", subtitle: ["Blueberry Eyes (feat. SUGA of BTS)", "Love Me Less (feat. Quinn XCII)", "Lights Down Low", "Take Over", "Checklist (feat. Chromeo)", "Satisfied"], image: UIImage(named: "max.jpg"), genre: "Pop", sound: "", soundTitle: "Now Playing: Love Me Less (feat. Quinn XCII) - MAX", bio: "Multiplatinum Sony recording artist MAX has been labeled a “Young Pop God” by GQ, named a “top popstar to watch” by Billboard and was nominated for “Best New Pop Artist” at the 2019 iHeartRadio Music Awards. Since the breakout success of his first full-length album “Hell’s Kitchen Angel,” MAX has garnered more than 1.2 billion streams and has toured the world multiple times over."),
         SwipeSelectorModel(title: "Enjoy the Playlist ✌️", subtitle: ["Enjoy the playlist"], image: UIImage(named: "playlist"), genre: "your music taste is 👌", sound: "", soundTitle: "", bio:"")
    ]
    
    public let overflowItem: SwipeSelectorModel = SwipeSelectorModel(title: "Tap to Make a New Playlist", subtitle: [""], image: UIImage(named: "playlist"), genre: "", sound: "", soundTitle: "", bio:"Not here...")
    
}
